language:   c
os:         linux
dist:       xenial
#sudo:       false
compiler:
  - gcc
  - clang

#branches:
#  only:
#    - master
#    - debug

script:
  - make
  - echo $?
  - ls -la pam2control.so
