language:   c
os:         linux
dist:       xenial
#sudo:       false
compiler:
  - gcc
  - clang

#branches:
#  only:
#    - master
#    - debug

script:
  - cd src
  - make
  - ls -la pam2control.so
  - sha256 pam2control.so
  - nm pam2control.so
